# Generated by Django 5.2.11 on 2026-02-09 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('video_url', models.CharField(db_index=True, max_length=500, unique=True)),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('uploaded_date', models.DateField(blank=True, db_index=True, null=True)),
                ('extra_metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-uploaded_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VideoExtendedMetadata',
            fields=[
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extended', serialize=False, to='main.video')),
                ('frame_count', models.BigIntegerField(blank=True, null=True)),
                ('pixel_format', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('bit_depth', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('container_format', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('audio_sample_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('audio_bitrate', models.BigIntegerField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoTechnicalMetadata',
            fields=[
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tech', serialize=False, to='main.video')),
                ('resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('orientation', models.CharField(blank=True, choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')], db_index=True, max_length=20, null=True)),
                ('duration_ms', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('fps', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('bitrate', models.BigIntegerField(blank=True, null=True)),
                ('video_codec', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('audio_codec', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('audio_channels', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='main.videocategory'),
        ),
        migrations.CreateModel(
            name='VideoFrame',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('frame_s3_key', models.CharField(max_length=700, unique=True)),
                ('frame_number', models.PositiveIntegerField()),
                ('timestamp_ms', models.BigIntegerField(blank=True, null=True)),
                ('frame_type', models.CharField(choices=[('key', 'Key Frame'), ('thumb', 'Thumbnail')], db_index=True, default='key', max_length=20)),
                ('thumbnail_score', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='main.video')),
            ],
            options={
                'ordering': ['video_id', 'frame_number'],
            },
        ),
        migrations.CreateModel(
            name='VideoProcessingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('metadata_extracted', models.BooleanField(default=False)),
                ('frames_extracted', models.BooleanField(default=False)),
                ('thumbnails_generated', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing', to='main.video')),
            ],
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['category', 'uploaded_date'], name='main_video_categor_3a2c52_idx'),
        ),
        migrations.AddIndex(
            model_name='videoframe',
            index=models.Index(fields=['video', 'frame_number'], name='main_videof_video_i_11ff47_idx'),
        ),
        migrations.AddIndex(
            model_name='videoframe',
            index=models.Index(fields=['video', 'frame_type'], name='main_videof_video_i_6ce823_idx'),
        ),
        migrations.AddConstraint(
            model_name='videoframe',
            constraint=models.UniqueConstraint(fields=('video', 'frame_number'), name='unique_frame_per_video'),
        ),
    ]
