# Generated by Django 5.2.11 on 2026-02-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoframe',
            name='timestamp_ms',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
