# Generated by Django 5.2.11 on 2026-02-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_videoframe_timestamp_ms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoframe',
            name='thumbnail_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
