# Generated by Django 5.2.11 on 2026-02-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_videoframe_thumbnail_score'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='video',
            new_name='video_categor_218f74_idx',
            old_name='main_video_categor_3a2c52_idx',
        ),
        migrations.RenameIndex(
            model_name='videoframe',
            new_name='video_frame_video_i_39da6d_idx',
            old_name='main_videof_video_i_11ff47_idx',
        ),
        migrations.RenameIndex(
            model_name='videoframe',
            new_name='video_frame_video_i_cc329c_idx',
            old_name='main_videof_video_i_6ce823_idx',
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['category', 'uploaded_date', 'id'], name='video_categor_d094a3_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['uploaded_date', 'id'], name='video_uploade_ad7276_idx'),
        ),
        migrations.AddIndex(
            model_name='videoextendedmetadata',
            index=models.Index(fields=['container_format', 'audio_bitrate'], name='video_exten_contain_ad737e_idx'),
        ),
        migrations.AddIndex(
            model_name='videoframe',
            index=models.Index(fields=['video', 'frame_type', 'frame_number'], name='video_frame_video_i_22980a_idx'),
        ),
        migrations.AddIndex(
            model_name='videoprocessingstate',
            index=models.Index(fields=['status', 'retry_count'], name='video_proce_status_b561c6_idx'),
        ),
        migrations.AddIndex(
            model_name='videoprocessingstate',
            index=models.Index(fields=['status', 'updated_at'], name='video_proce_status_ad52e7_idx'),
        ),
        migrations.AddIndex(
            model_name='videotechnicalmetadata',
            index=models.Index(fields=['orientation', 'duration_ms'], name='video_techn_orienta_3225a5_idx'),
        ),
        migrations.AddIndex(
            model_name='videotechnicalmetadata',
            index=models.Index(fields=['video_codec', 'audio_codec'], name='video_techn_video_c_742fc3_idx'),
        ),
        migrations.AlterModelTable(
            name='video',
            table='video',
        ),
        migrations.AlterModelTable(
            name='videocategory',
            table='video_category',
        ),
        migrations.AlterModelTable(
            name='videoextendedmetadata',
            table='video_extended_metadata',
        ),
        migrations.AlterModelTable(
            name='videoframe',
            table='video_frame',
        ),
        migrations.AlterModelTable(
            name='videoprocessingstate',
            table='video_processing_state',
        ),
        migrations.AlterModelTable(
            name='videotechnicalmetadata',
            table='video_technical_metadata',
        ),
    ]
